name: 'Managed trusted sources of managed database (digital ocean)'
description: 'Add or remove your runner public IP address to the trusted source of your digital ocean managed database'
branding:
  icon: database
  color: blue
inputs:
  action:
    description: 'add or remove'
    required: true
  database_id:
    description: 'The uuid of the managed database'
    required: true
  digitalocean_token:
    description: 'Digital Access Token'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
